### ISSUE TITLE
Anonymous User Creation prevents API from running

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/resources-portal#311]
### Context

I was unable to run the api server via `rportal up` with the following error occurring.
```
resources_portal_api | Traceback (most recent call last):
resources_portal_api |   File "/usr/local/lib/python3.8/site-packages/guardian/management/__init__.py", line 32, in create_anonymous_user
resources_portal_api |     User.objects.using(kwargs['using']).get(**lookup)
resources_portal_api |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
resources_portal_api |     raise self.model.DoesNotExist(
resources_portal_api | resources_portal.models.user.DoesNotExist: User matching query does not exist.
resources_portal_api |
resources_portal_api | During handling of the above exception, another exception occurred:
resources_portal_api |
resources_portal_api | Traceback (most recent call last):
resources_portal_api |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
resources_portal_api |     return self.cursor.execute(sql, params)
resources_portal_api | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "resources_portal_user_orcid_key"
resources_portal_api | DETAIL:  Key (orcid)=() already exists.
```
### Problem or idea

Apparently when creating an anonymous user it places one in the DB? This might happen everytime the server is restarted as well.

### Solution or next step

There are ways to override how the anonymous user is created and there are other ways to get around this. I think it makes sense to have the field be unique but nullable since it is possible we will want other auth types as well without `orcid`.

[anonomous-user-creation](https://django-guardian.readthedocs.io/en/stable/userguide/custom-user-model.html?highlight=unique%20fields#anonymous-user-creation)

`models/user.py`
```python 
-    orcid = models.TextField(unique=True)
+    orcid = models.TextField(unique=True, null=True)
```

**Comment by davidsmejia** [comment]
I'll PR for this later but for now I want to keep the changes in my current branch so I can dev against my local API
